### ISSUE TITLE
Failed to install: dependency ring was yanked from crates.io

### ISSUE THREAD

**Issue by dmix** [iqlusioninc/sear#14]
The version of `ring` being used has been yanked by the author and needs to be upgraded:

https://crates.io/crates/ring/versions

```
 cargo install sear
    Updating crates.io index
  Downloaded sear v0.0.0
  Downloaded 1 crate (1.3 KB) in 1.93s
  Installing sear v0.0.0
error: failed to compile `sear v0.0.0`, intermediate artifacts can be found at `/var/folders/l6/x22njlt51m991f0vx6xd37nh0000gn/T/cargo-installZY8nNO`

Caused by:
  failed to select a version for the requirement `ring = "^0.12"`
  candidate versions found which didn't match: 0.14.6, 0.14.5, 0.14.4, ...
  location searched: crates.io index
required by package `sear v0.0.0`
```

**Comment by tarcieri** [comment]
@dmix yeah, there's no actual release yet. Perhaps I should yank the `v0.0.0` crate and update the README to better clarify.

**Comment by dmix** [comment]
I wouldn't bother on my account I was just looking for abscissa examples which this seems inspired by. 

FYI I'm using abscissa for https://github.com/dmix/portal which I hope to release next month

**Comment by tarcieri** [comment]
Nice!
