### ISSUE TITLE
[Question] Security Guarantees

### ISSUE THREAD

**Issue by elimisteve** [iqlusioninc/sear#15]
With sear's construction, is it possible for an attacker viewing the ciphertext (a sear archive) to tell how many files it contains?

Thanks!

**Comment by tarcieri** [comment]
The index of the archive is stored in the encrypted part of the footer:

https://github.com/iqlusioninc/sear/blob/develop/protos/footers.proto#L33

It's not readily visible, however the length of the encrypted part of the footer is both unencrypted and primarily determined by the number of entries in it (in combination with the length of each path), so there is certainly potential for determining this information via a length sidechannel.

If the files all have fixed-sized paths, and the attacker knows how long they are (and knows or can guess the general structure of the rest of the metadata), computing the number of the files in the archive can be done fairly accurately by dividing the size of each entry in encrypted footer by its length.

One way to potentially mitigate this is by padding the encrypted part of the footer.

**Comment by elimisteve** [comment]
Thank you :+1:
