### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by zmarouf** [iqlusioninc/sear#6]
Hello,

Very cool tool. I was wondering if you considered options to allow reproducible archives.
From what I understand, it would involve fixing the UUID and creation Date.
Or am I missing something?

**Comment by alerque** [comment]
Wouldn't this also imply deterministic encryption?

**Comment by zmarouf** [comment]
My crypto knowledge is close to nonexistent so please correct me if I'm wrong: I thought the encryption process itself was done with fixed generated keys. Are you saying that they're actually generated each run and not reusable at all?

**Comment by tarcieri** [comment]
The STREAM construction as instantiated by Tink includes random nonces, in addition to the one included in each archive (the UUID).

These are necessary as encrypting two messages under the same key/nonce combination with AES-GCM leaks the XOR of the original plaintexts and the GMAC authentication key.
